// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClqY7f616W9eENfJ832br7E4ZvyxVZD1Q',
    appId: '1:224664773282:web:5ad4773931262879ed6dfb',
    messagingSenderId: '224664773282',
    projectId: 'hobby-mate-40752',
    authDomain: 'hobby-mate-40752.firebaseapp.com',
    storageBucket: 'hobby-mate-40752.appspot.com',
    measurementId: 'G-0V5C0DZFRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXDG_6v9vTahRnCKQ6CV4RbPXvYvUQqAI',
    appId: '1:224664773282:android:ad97756bd4ff13baed6dfb',
    messagingSenderId: '224664773282',
    projectId: 'hobby-mate-40752',
    storageBucket: 'hobby-mate-40752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4mq1THm_eZhnWjy6sT5-HwiS8aM5e8vA',
    appId: '1:224664773282:ios:b09c81643ffc479fed6dfb',
    messagingSenderId: '224664773282',
    projectId: 'hobby-mate-40752',
    storageBucket: 'hobby-mate-40752.appspot.com',
    iosClientId: '224664773282-t207i4kom6ammgmdrd6l0ehpe8egp4o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobbyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4mq1THm_eZhnWjy6sT5-HwiS8aM5e8vA',
    appId: '1:224664773282:ios:b09c81643ffc479fed6dfb',
    messagingSenderId: '224664773282',
    projectId: 'hobby-mate-40752',
    storageBucket: 'hobby-mate-40752.appspot.com',
    iosClientId: '224664773282-t207i4kom6ammgmdrd6l0ehpe8egp4o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobbyMate',
  );
}
